image:
  file: .gitpod.Dockerfile

tasks:
  - init: pnpm install && pnpm dev
    command: pnpm dev

ports:
  - port: 3000
    onOpen: open-browser
    visibility: public

vscode:
  extensions:
    - svelte.svelte-vscode
    - bradlc.vscode-tailwindcss
    - heybourn.headwind